services:
  skipbot:
    build: .
    container_name: skipbot
    restart: unless-stopped
    volumes:
      - db_data:/app
    env_file:
      - .env

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
